@startuml

namespace Item.Chest {

    class ChestController {
        -ItemEntity item
        +Start()
            item = ItemService.rand()
        +OnTriggerEnter()
            item.show(Chest位置をVector3で渡す)
    }

}

@enduml